// Conteúdo inicial dos POPs (instrução 09), importado uma única vez pelo servidor (idempotente).
// v1 publicada = texto original exportado do ClickUp (seção 6 da instrução), sem completar nada.
// v2 rascunho = versão aprimorada, aguardando a revisão do Mestre (nunca publicada automaticamente).
// Passo: { t: texto, n: 0 | 1 (subitem) }. Atividade: { nome, quando?, passos, ferramentas?, pronto?, duvidas? }.
const p = t => ({ t, n: 0 });
const s = t => ({ t, n: 1 });
const NV = "[CONTEÚDO NÃO VEIO NA EXPORTAÇÃO]";
const CU = "https://app.clickup.com/9013068617/docs/8ckh0u9-24353/";

export const FUNCOES_POP = {
  atendimento: "Atendimento", social: "Social media", diretor_arte: "Design & Criação",
  coordenador: "Coordenação", gestao: "Gestão", plataformas: "Uso das plataformas",
};

// ---------------------------------------------------------------- v1 (publicada, fiel à exportação)
export const V1 = {
  atendimento: {
    titulo: "POP — Atendimento",
    introducao: "Este guia demonstra o procedimento padrão para os colaboradores no setor de Atendimento.",
    links: [{ rotulo: "Link ClickUp (privado)", url: CU + "8ckh0u9-17913" }, { rotulo: "Link ClickUp (privado)", url: CU + "8ckh0u9-17893" }],
    linksTitulo: "Confira também",
    atividades: [
      { nome: "Checagem dos grupos dos clientes", passos: [p(NV)] },
      { nome: "Comunicação com os Sociais Media dos clientes", passos: [p(NV)] },
      { nome: "Conferência do andamento dos planejamentos", passos: [p(NV)] },
      { nome: "Desenvolver e conferir materiais OOH", passos: [p(NV)] },
    ],
  },
  social: {
    titulo: "POP — Social Media",
    introducao: "Este guia demonstra o procedimento padrão para os colaboradores no setor de Social Media.",
    links: [{ rotulo: "Link ClickUp (privado)", url: CU + "8ckh0u9-17573" }],
    linksTitulo: "Veja também",
    atividades: [
      { nome: "Checagem dos grupos dos clientes", passos: [p(NV)] },
      { nome: "Desenvolvimento", passos: [
        p("Dentro do planejamento do cliente, criar uma nova subtarefa com os campos: IDEIA, TEXTO/REDAÇÃO, FOTO SUGESTÃO e LEGENDA."),
        p("🌐 Uso do ClickUp: para enviar a demanda para o Designer, adicione uma data de vencimento e preencha o campo Designer."),
        p("Confira a Pauta dos designers: https://app.clickup.com/9013068617/v/b/8ckh0u9-28533"),
        p("Produzir o material tendo como objetivo: " + NV)] },
      { nome: "Aprovação", passos: [
        p("Ao receber o link do material aprovado internamente, envie para aprovação do cliente no grupo do WhatsApp ou via mLabs."),
        p("Em caso de envio como link, conferir a privacidade de compartilhamento, que deve estar definida como público (visível para qualquer pessoa com link)."),
        p("🌐 Uso do ClickUp: mudar o status para \"Enviado\"."),
        p("Em caso de alteração solicitada pelo cliente: descreva as alterações no campo de comentários da tarefa, mencione o Designer, defina uma nova data de vencimento e mude o status para \"Para Alteração\". Ao receber o material atualizado, repita o processo de Aprovação e, caso aprovado, siga para a Postagem.")] },
      { nome: "Agendamento e postagem", passos: [p("Siga para postagem manual ou confira e confirme o agendamento via mLabs.")] },
    ],
  },
  diretor_arte: {
    titulo: "POP — Design & Criação",
    introducao: "Este guia demonstra o procedimento padrão para os colaboradores no setor de Design & Criação.",
    links: [{ rotulo: "Link ClickUp (privado)", url: CU + "8ckh0u9-17933" }, { rotulo: "Link ClickUp (privado)", url: CU + "8ckh0u9-17953" }],
    linksTitulo: "Confira também",
    atividades: [
      { nome: "Checagem da pauta e início da produção", passos: [p("Iniciar a produção dos materiais da pauta, por ordem de horário e prioridade. Cumprir o horário de entrega.")] },
      { nome: "Desenvolvimento", passos: [
        p("🌐 Uso do ClickUp: mudar o status da subtarefa para \"Em Andamento\" no momento em que iniciar a produção. Ligar o rastreamento de tempo."),
        p("Produzir o material tendo como objetivo: " + NV)] },
      { nome: "Aprovação", passos: [
        p("Enviar no canal do Discord o material produzido para aprovação."),
        p("🌐 Uso do ClickUp: mudar o status para \"Em Revisão\". Parar o rastreamento de tempo."),
        p("Realizar possíveis alterações com celeridade e empenho para resolver as questões apontadas, visando entregar o material de forma satisfatória."),
        p("Cobrar os responsáveis pela aprovação dos materiais, para que os mesmos sejam liberados no mesmo dia em que foram submetidos para aprovação.")] },
      { nome: "Liberação", passos: [
        p("Liberar o material em forma de link nos comentários da tarefa. Mencionar o Social Media."),
        p("🌐 Uso do ClickUp: manter o status para \"Em Revisão\", não alterar."),
        p("A privacidade do link deve ser configurada para estar acessível para todos que possuem o link."),
        p("Em caso de material com vários arquivos, como carrossel, criar uma pasta com a mesma numeração do material e liberar o link da pasta.")] },
    ],
  },
  plataformas: {
    titulo: "POP — Uso das plataformas",
    introducao: "Plataformas usadas pela equipe (os nomes das ferramentas foram deduzidos dos outros POPs; confirme com o Mestre na revisão):",
    links: [], atividades: [],
    plataformas: [
      { nome: "ClickUp (nome deduzido)", funcao: "Plataforma de organização de demandas", link: CU + "8ckh0u9-17553" },
      { nome: "Discord (nome deduzido)", funcao: "Canal de comunicação interno e aprovação de materiais", link: CU + "8ckh0u9-17653" },
      { nome: "Armazenamento em nuvem (nome da ferramenta não informado; provavelmente Google Drive)", funcao: "Nosso armazenamento em nuvem", link: CU + "8ckh0u9-17613" },
      { nome: "Canal com clientes (nome não informado; os POPs citam WhatsApp e mLabs)", funcao: "Canal de comunicação com os clientes", link: CU + "8ckh0u9-17673" },
    ],
  },
};

// ---------------------------------------------------------------- v2 (rascunho aprimorado)
const DUVIDA = "[CONFIRMAR: a quem recorrer em caso de dúvida (coordenação ou gestão) e por qual canal]";
export const V2 = {
  atendimento: {
    titulo: "POP — Atendimento",
    introducao: "Objetivo da função: cuidar da relação com cada cliente da carteira, mantendo a comunicação em dia, encaminhando as demandas para a equipe e acompanhando cada envio até o retorno do cliente.\n\nEste guia traz, para cada atividade, quando ela acontece, o passo a passo em checklist, as ferramentas, o critério de \"pronto\" e quem acionar em caso de dúvida. Os trechos marcados [CONFIRMAR] dependem de definição do Mestre.",
    links: V1.atendimento.links, linksTitulo: "Confira também",
    atividades: [
      { nome: "Começo do dia: Minhas tarefas", quando: "Todo dia, ao começar o expediente. [CONFIRMAR: horário de início]",
        passos: [p("Abrir a Central Quinze > 01 Atendimento > **Minhas tarefas**, na visão **Hoje** (prazo de hoje, atrasadas e sem prazo)."),
          p("Começar pelas tarefas atrasadas e pelas de prioridade alta."),
          p("Registrar como tarefa todo pedido novo que chegar no dia, com o cliente e o prazo."),
          s("Tarefas que se repetem (ex.: checagem diária) podem ser criadas com \"repetir\": ao concluir, a próxima é criada sozinha."),
          p("Marcar cada tarefa como concluída assim que terminar.")],
        ferramentas: "Central Quinze: Minhas tarefas", pronto: "Lista do dia revisada e atualizada; nada feito ficou sem marcar.", duvidas: DUVIDA },
      { nome: "Checagem dos grupos dos clientes", quando: "Diariamente. [CONFIRMAR: horários fixos de checagem, por exemplo início da manhã, depois do almoço e fim da tarde]",
        passos: [p("Abrir o grupo de WhatsApp de cada cliente da sua carteira (a lista está em 01 Atendimento > **Clientes**)."),
          p("Ler as mensagens novas desde a última checagem. Em cada grupo, olhar:"),
          s("pedidos novos do cliente;"), s("respostas a envios que estavam aguardando retorno;"), s("dúvidas e reclamações;"),
          s("[CONFIRMAR: outros pontos a observar em cada grupo]"),
          p("Responder ou dar um prazo de resposta ao cliente. [CONFIRMAR: tempo máximo para responder o cliente]"),
          p("Pedido novo: registrar em **Minhas tarefas**, com cliente e prazo."),
          p("Resposta a um envio: registrar o retorno em **Pendências de clientes**."),
          p("Reclamação: registrar em 04 CS > **Reclamações**.")],
        ferramentas: "WhatsApp (grupos dos clientes); Central Quinze: Clientes, Minhas tarefas, Pendências de clientes, Reclamações",
        pronto: "Todos os grupos lidos; nenhuma mensagem do cliente sem resposta ou sem prazo; pedidos e retornos registrados na Central.", duvidas: DUVIDA },
      { nome: "Comunicação com os Social Medias dos clientes", quando: "[CONFIRMAR: sempre que houver pedido do cliente e/ou em reunião fixa]",
        passos: [p("Conferir na Carteira (01 Atendimento > **Clientes**) quem é o social media responsável pelo cliente."),
          p("Repassar o pedido com o contexto completo, o prazo combinado com o cliente e os links necessários."),
          p("[CONFIRMAR: canal oficial do repasse ao social media (ClickUp, grupo interno ou outro)]"),
          p("Acompanhar até a entrega e devolver o retorno ao cliente.")],
        ferramentas: "Central Quinze: Clientes; [CONFIRMAR: ferramenta de repasse]", pronto: "Social media ciente do pedido, com prazo e contexto; cliente informado do prazo.", duvidas: DUVIDA },
      { nome: "Conferência do andamento dos planejamentos", quando: "[CONFIRMAR: frequência da conferência (semanal, quinzenal) e data limite do planejamento mensal]",
        passos: [p("Abrir 01 Atendimento > **Andamento de produção** e conferir o andamento de cada cliente da sua carteira."),
          p("[CONFIRMAR: o que conta como planejamento em dia]"),
          p("Planejamento atrasado: falar com o social media responsável e combinar nova data."),
          p("Atraso que afete o cliente: avisar o cliente e a gestão. [CONFIRMAR]")],
        ferramentas: "Central Quinze: Andamento de produção", pronto: "Todos os clientes da carteira com planejamento conferido e atrasos tratados.", duvidas: DUVIDA },
      { nome: "Desenvolver e conferir materiais OOH", quando: "Sempre que o cliente tiver material de mídia exterior ou offline (outdoor, busdoor, panfleto, banner, impressos).",
        passos: [p("[CONFIRMAR: etapas de desenvolvimento do material OOH (briefing, medidas, fornecedor/gráfica, prazos)]"),
          p("Antes de enviar ao cliente, conferir:"),
          s("medidas e formato pedidos pelo fornecedor;"), s("textos, telefones, endereços e logo;"), s("[CONFIRMAR: demais itens do checklist de conferência]"),
          p("Enviar ao cliente e registrar em 01 Atendimento > **Pendências de clientes** (a Central classifica como Material OOH/offline e gera a mensagem para copiar)."),
          p("Quando o cliente responder, registrar o retorno na pendência.")],
        ferramentas: "Central Quinze: Pendências de clientes; [CONFIRMAR: ferramentas de produção]", pronto: "Material conferido, enviado, registrado como pendência e com retorno registrado.", duvidas: DUVIDA },
      { nome: "Envios que dependem de retorno do cliente", quando: "Sempre que enviar ao cliente algo que precise de resposta (aprovação, orçamento, informação); conferência diária das atrasadas.",
        passos: [p("Em 01 Atendimento > **Pendências de clientes**, clicar em \"Nova pendência\", colar o link, escolher o cliente e interpretar."),
          s("Link privado: a Central pede uma descrição de uma linha e indica que a classificação foi feita só pela descrição."),
          p("Conferir o tipo, o título, o prazo de retorno e a mensagem; editar se precisar."),
          p("Clicar em \"Aprovar e copiar mensagem\" e colar no WhatsApp do cliente. A Central não envia nada sozinha."),
          p("Acompanhar as pendências atrasadas (destacadas na planilha; também viram tarefa em Minhas tarefas) e usar \"Gerar cobrança\"."),
          p("Registrar o retorno (respondida, aprovada ou recusada) assim que o cliente responder.")],
        ferramentas: "Central Quinze: Pendências de clientes, Minhas tarefas; WhatsApp", pronto: "Todo envio registrado; nenhuma pendência atrasada sem cobrança; retornos registrados no dia.", duvidas: DUVIDA },
      { nome: "Fim do dia e relatório das 20h", quando: "Todo dia útil, antes das 20h.",
        passos: [p("Marcar como concluídas as tarefas feitas e ajustar o prazo das que ficaram para depois."),
          p("Às 20h a Central envia no WhatsApp o resumo do dia, com o que cada atendimento fez, o que ficou pendente e as pendências de clientes sem retorno.")],
        ferramentas: "Central Quinze: Minhas tarefas", pronto: "Lista do dia atualizada antes do relatório.", duvidas: DUVIDA },
      { nome: "Onboarding de novos clientes", quando: "Quando um cliente novo entra na carteira.",
        passos: [p("Conduzir o onboarding em 01 Atendimento > **Onboarding**, etapa por etapa."), p("[CONFIRMAR: prazos de cada etapa e responsáveis]")],
        ferramentas: "Central Quinze: Onboarding", pronto: "Todas as etapas do onboarding concluídas na Central.", duvidas: DUVIDA },
      { nome: "Reuniões, propostas e pesquisas", quando: "[CONFIRMAR]",
        passos: [p("Reuniões com clientes: registrar em 01 Atendimento > **Agenda**."),
          p("Propostas comerciais: ficam em 01 Atendimento > **Propostas**. [CONFIRMAR: papel do atendimento nas propostas]"),
          p("Pesquisa de satisfação: quando solicitada, usar 04 CS > **NPS Pesquisa** e enviar ao cliente a mensagem pronta. [CONFIRMAR: periodicidade]")],
        ferramentas: "Central Quinze: Agenda, Propostas, NPS Pesquisa", duvidas: DUVIDA },
    ],
  },
  social: {
    titulo: "POP — Social Media",
    introducao: "Objetivo da função: planejar, redigir e publicar os conteúdos dos clientes, cuidando da aprovação interna e do cliente até a postagem.\n\nCada atividade traz quando acontece, o passo a passo, as ferramentas, o critério de \"pronto\" e quem acionar em caso de dúvida. Os trechos [CONFIRMAR] dependem de definição do Mestre.",
    links: V1.social.links, linksTitulo: "Veja também",
    atividades: [
      { nome: "Checagem dos grupos dos clientes", quando: "[CONFIRMAR: horários fixos de checagem]",
        passos: [p("Abrir o grupo de WhatsApp de cada cliente sob sua responsabilidade (a lista está em 01 Atendimento > **Clientes**)."),
          p("Ler as mensagens novas: pedidos de conteúdo, respostas de aprovação e ajustes."), p("[CONFIRMAR: o que o social media responde direto e o que repassa ao atendimento]")],
        ferramentas: "WhatsApp; Central Quinze: Clientes", pronto: "Grupos lidos e pedidos encaminhados.", duvidas: DUVIDA },
      { nome: "Desenvolvimento", quando: "Conforme o planejamento do cliente. [CONFIRMAR: antecedência mínima em relação à data de postagem]",
        passos: [p("Dentro do planejamento do cliente, criar uma nova subtarefa com os campos: IDEIA, TEXTO/REDAÇÃO, FOTO SUGESTÃO e LEGENDA."),
          p("🌐 Uso do ClickUp: para enviar a demanda para o Designer, adicione uma data de vencimento e preencha o campo Designer."),
          p("Confira a Pauta dos designers: https://app.clickup.com/9013068617/v/b/8ckh0u9-28533"),
          p("Produzir o material tendo como objetivo: [CONFIRMAR: objetivo do material (ex.: alinhado ao planejamento e à identidade do cliente)]")],
        ferramentas: "ClickUp", pronto: "Subtarefa criada com os 4 campos, data de vencimento e Designer preenchidos.", duvidas: DUVIDA },
      { nome: "Aprovação interna", quando: "Quando o material sai do Design.",
        passos: [p("A peça passa pela aprovação interna na Central Quinze, em 02 Aprovação de peças: quem envia usa **Envio**, e o coordenador, o Mestre ou a gestão decidem na **Fila de aprovação** (aprovar, reprovar ou pedir alteração, com comentário)."),
          p("Alteração pedida internamente: o comentário aparece na peça; a nova versão é reenviada pela própria Central."),
          p("[CONFIRMAR: se a aprovação interna passa a ser só pela Central ou continua também pelo Discord]")],
        ferramentas: "Central Quinze: Aprovação de peças", pronto: "Peça aprovada internamente.", duvidas: DUVIDA },
      { nome: "Aprovação do cliente", quando: "Logo após a aprovação interna.",
        passos: [p("Ao receber o link do material aprovado internamente, envie para aprovação do cliente no grupo do WhatsApp ou via mLabs."),
          p("Em caso de envio como link, conferir a privacidade de compartilhamento, que deve estar definida como público (visível para qualquer pessoa com link)."),
          p("🌐 Uso do ClickUp: mudar o status para \"Enviado\"."),
          p("Em caso de alteração solicitada pelo cliente:"),
          s("descreva as alterações no campo de comentários da tarefa;"), s("mencione o Designer;"), s("defina uma nova data de vencimento;"), s("mude o status para \"Para Alteração\"."),
          p("Ao receber o material atualizado, repita o processo de Aprovação e, caso aprovado, siga para a Postagem.")],
        ferramentas: "WhatsApp ou mLabs; ClickUp", pronto: "Cliente aprovou e o status no ClickUp está atualizado.", duvidas: DUVIDA },
      { nome: "Agendamento e postagem", quando: "Na data prevista no planejamento.",
        passos: [p("Siga para postagem manual ou confira e confirme o agendamento via mLabs."), p("[CONFIRMAR: status final no ClickUp depois da postagem]")],
        ferramentas: "mLabs; ClickUp", pronto: "Post publicado ou agendado e conferido.", duvidas: DUVIDA },
    ],
  },
  diretor_arte: {
    titulo: "POP — Design & Criação",
    introducao: "Objetivo da função: produzir os materiais da pauta dentro do horário de entrega, com qualidade, passando pela aprovação interna e liberando o material para o Social Media.\n\nCada atividade traz quando acontece, o passo a passo, as ferramentas, o critério de \"pronto\" e quem acionar em caso de dúvida. Os trechos [CONFIRMAR] dependem de definição do Mestre.",
    links: V1.diretor_arte.links, linksTitulo: "Confira também",
    atividades: [
      { nome: "Checagem da pauta e início da produção", quando: "Todo dia, ao começar o expediente. [CONFIRMAR: horário]",
        passos: [p("Conferir a pauta do dia no ClickUp."), p("Iniciar a produção dos materiais da pauta, por ordem de horário e prioridade. Cumprir o horário de entrega.")],
        ferramentas: "ClickUp", pronto: "Pauta conferida e produção iniciada pela prioridade.", duvidas: DUVIDA },
      { nome: "Desenvolvimento", quando: "Durante a produção de cada material.",
        passos: [p("🌐 Uso do ClickUp: mudar o status da subtarefa para \"Em Andamento\" no momento em que iniciar a produção. Ligar o rastreamento de tempo."),
          p("Produzir o material tendo como objetivo: [CONFIRMAR: objetivo do material (ex.: briefing atendido e identidade visual do cliente)]")],
        ferramentas: "ClickUp; [CONFIRMAR: ferramentas de criação]", pronto: "Material produzido conforme a subtarefa.", duvidas: DUVIDA },
      { nome: "Aprovação interna", quando: "Ao terminar o material.",
        passos: [p("Enviar o material para aprovação:"),
          s("na Central Quinze: 02 Aprovação de peças > **Envio** (até 10 arquivos JPG, PNG ou PDF por versão, e links do Google Drive). Os arquivos ficam disponíveis por 7 dias;"),
          s("no canal do Discord, como hoje. [CONFIRMAR: se o Discord continua sendo usado junto com a Central]"),
          p("🌐 Uso do ClickUp: mudar o status para \"Em Revisão\". Parar o rastreamento de tempo."),
          p("Alteração pedida: o comentário de quem aprovou aparece na peça. Realizar as alterações com celeridade e empenho e reenviar pela Central (vira a versão 2 da mesma peça)."),
          p("Cobrar os responsáveis pela aprovação dos materiais, para que os mesmos sejam liberados no mesmo dia em que foram submetidos para aprovação.")],
        ferramentas: "Central Quinze: Aprovação de peças; Discord; ClickUp", pronto: "Peça aprovada no mesmo dia do envio.", duvidas: DUVIDA },
      { nome: "Liberação", quando: "Depois da aprovação interna.",
        passos: [p("Liberar o material em forma de link nos comentários da tarefa. Mencionar o Social Media."),
          p("🌐 Uso do ClickUp: manter o status para \"Em Revisão\", não alterar."),
          p("A privacidade do link deve ser configurada para estar acessível para todos que possuem o link."),
          p("Em caso de material com vários arquivos, como carrossel, criar uma pasta com a mesma numeração do material e liberar o link da pasta.")],
        ferramentas: "ClickUp; armazenamento em nuvem [CONFIRMAR: Google Drive]", pronto: "Link liberado na tarefa, com privacidade correta e Social Media mencionado.", duvidas: DUVIDA },
    ],
  },
  plataformas: {
    titulo: "POP — Uso das plataformas",
    introducao: "Ferramentas que a equipe usa no dia a dia, para que serve cada uma e onde encontrar. Os nomes marcados [CONFIRMAR] foram deduzidos dos POPs e precisam ser confirmados pelo Mestre.",
    links: [], atividades: [
      { nome: "Central Quinze: o que fica em cada módulo", quando: "Uso diário.",
        passos: [p("**01 Atendimento:** Carteira de clientes (Dashboard e Clientes), Onboarding, Propostas, Agenda, Andamento de produção, Minhas tarefas, Pendências de clientes e o Relatório das 20h (configurado pela gestão)."),
          p("**02 Aprovação de peças:** Envio, Fila de aprovação, Dashboard mensal e Dados consolidados."),
          p("**03 Administrativo** (Mestre e gestão): Contratos, Assinatura de documentos, Pessoal, Férias, Equipe (Equipe e ajustes e Usuários) e POP operacional."),
          p("**04 CS:** NPS Pesquisa, NPS Média e Reclamações."),
          p("**05 Políticas:** Código de ética (leitura obrigatória de cada versão, com \"Li e estou ciente\")."),
          p("**06 Financeiro** (Mestre e gestão)."),
          p("**Meu POP:** atalho na tela de módulos e no topo de cada módulo, com o POP da sua função e este guia de plataformas.")],
        ferramentas: "Central Quinze [CONFIRMAR: endereço oficial da Central]" },
    ],
    plataformas: [
      { nome: "Central Quinze", funcao: "Carteira de clientes, tarefas, pendências, aprovação de peças, CS, políticas e POPs", link: "[CONFIRMAR: endereço oficial da Central]" },
      { nome: "ClickUp [CONFIRMAR]", funcao: "Plataforma de organização de demandas", link: CU + "8ckh0u9-17553" },
      { nome: "Discord [CONFIRMAR]", funcao: "Canal de comunicação interno e aprovação de materiais", link: CU + "8ckh0u9-17653" },
      { nome: "Google Drive [CONFIRMAR]", funcao: "Nosso armazenamento em nuvem", link: CU + "8ckh0u9-17613" },
      { nome: "WhatsApp e mLabs [CONFIRMAR]", funcao: "Canal de comunicação com os clientes", link: CU + "8ckh0u9-17673" },
      { nome: "CRM WhatsApp", funcao: "[CONFIRMAR: para que a equipe usa o CRM WhatsApp]", link: "https://chatt.inteligentte.com.br/" },
    ],
  },
  // Rascunhos iniciais (nunca publicados): só o esqueleto e o que já é regra na Central.
  coordenador: {
    titulo: "POP — Coordenação",
    introducao: "Objetivo da função: [CONFIRMAR]\n\nEsqueleto inicial. Complete com a ajuda do botão \"Ajudar com o Claude\".",
    links: [], linksTitulo: "Confira também",
    atividades: [
      { nome: "Aprovação interna de peças", quando: "Sempre que houver peça pendente na fila. [CONFIRMAR: horários de conferência da fila]",
        passos: [p("Abrir a Central Quinze > 02 Aprovação de peças > **Fila de aprovação** (pendentes, incluindo as reenviadas)."),
          p("Para cada peça: aprovar, reprovar ou pedir alteração."),
          s("Reprovar e pedir alteração exigem comentário, que aparece para quem enviou."),
          s("Ninguém decide uma peça que ele mesmo enviou."),
          p("As decisões entram no Dashboard mensal da aprovação de peças."),
          p("[CONFIRMAR: prazo máximo para decidir uma peça]")],
        ferramentas: "Central Quinze: Aprovação de peças", pronto: "Fila sem peças pendentes ao fim do dia. [CONFIRMAR]", duvidas: DUVIDA },
      { nome: "[CONFIRMAR: demais atividades da coordenação]", passos: [p("[CONFIRMAR]")] },
    ],
  },
  gestao: {
    titulo: "POP — Gestão",
    introducao: "Objetivo da função: [CONFIRMAR]\n\nEsqueleto inicial. Complete com a ajuda do botão \"Ajudar com o Claude\".",
    links: [], linksTitulo: "Confira também",
    atividades: [
      { nome: "Módulo Administrativo", quando: "[CONFIRMAR]",
        passos: [p("Contratos: acompanhar status, vencimentos e renovações em 03 Administrativo > **Contratos**, incluindo os que chegam do onboarding marcados \"a conferir\"."),
          p("Assinatura de documentos, Pessoal e Férias: no mesmo módulo."), p("Equipe: listas de atendimentos e social medias e ajustes gerais em **Equipe e ajustes**; acessos à Central em **Usuários**."), p("[CONFIRMAR: rotina e frequência]")],
        ferramentas: "Central Quinze: Administrativo" },
      { nome: "Acompanhamento do Atendimento", quando: "[CONFIRMAR]",
        passos: [p("Ler o relatório das 20h no WhatsApp (feitas, pendentes e pendências de clientes sem retorno por atendimento)."),
          p("Conferir as pendências atrasadas por atendimento em 01 Atendimento > **Pendências de clientes**."),
          p("Criar tarefas para um atendimento em **Minhas tarefas**, quando necessário."), p("[CONFIRMAR]")],
        ferramentas: "Central Quinze: Relatório das 20h, Pendências de clientes, Minhas tarefas" },
      { nome: "Aprovação de peças", passos: [p("A gestão também decide peças na **Fila de aprovação** e acompanha o **Dashboard mensal**."), p("[CONFIRMAR: divisão com a coordenação]")] },
      { nome: "Financeiro", passos: [p("Contas a receber, contas a pagar, fluxo de caixa e dashboard em 06 **Financeiro**."), p("[CONFIRMAR: rotina]")] },
      { nome: "[CONFIRMAR: demais atividades da gestão]", passos: [p("[CONFIRMAR]")] },
    ],
  },
};
